export const styles = {
  sectionCard: {
    width: '100%',
    padding: '24px',
    marginBottom: '24px',
    borderRadius: '12px',
    boxShadow: '0px 2px 10px rgba(0, 0, 0, 0.1)',
  },
  analysisContent: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '24px',
  },
  scoreBoard: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
  },
  scoreCardRed: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '12px 16px',
    borderRadius: '8px',
    boxShadow: '0px 2px 6px rgba(0, 0, 0, 0.1)',
    width: '180px',
    backgroundColor: 'rgba(255, 85, 85, 0.1)',
  },
  scoreCardYellow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '12px 16px',
    borderRadius: '8px',
    boxShadow: '0px 2px 6px rgba(0, 0, 0, 0.1)',
    width: '180px',
    backgroundColor: 'rgba(255, 178, 30, 0.1)',
  },
  scoreCardBlue: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '12px 16px',
    borderRadius: '8px',
    boxShadow: '0px 2px 6px rgba(0, 0, 0, 0.1)',
    width: '180px',
    backgroundColor: 'rgba(0, 187, 143, 0.1)',
  },
  scoreCardViolet: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '12px 16px',
    borderRadius: '8px',
    boxShadow: '0px 2px 6px rgba(0, 0, 0, 0.1)',
    width: '180px',
    backgroundColor: 'rgba(17, 37, 214, 0.1)',
  },
}
